---
- name: Install Pre-requisites
  package: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  tags: Debian
  with_items:
  - curl
  - apt-transport-https

- name: Install JRE
  package: name={{ riak_java_package }} state=present update_cache=yes cache_valid_time=3600
  tags: Debian
  when: 'riak_install_java and riak_java_package is defined'

- name: Install JRE
  package: name=default-jre state=present update_cache=yes cache_valid_time=3600
  tags: Debian
  when: 'riak_install_java and riak_java_package is undefined'

- name: Check if Riak is installed
  stat: path=/etc/riak/riak.conf
  register: dist

#- name: Add Package Cloud repository key without validation
#  apt_key: url=https://packagecloud.io/gpg.key state=present validate_certs=no
#  tags: Debian
#  when:
#    - not dist.stat.exists
#    - riak_install_package_cloud

#- name: Add Basho Riak repository (hosted at Package Cloud)
#  template: src=deb_repo.list.j2 dest=/etc/apt/sources.list.d/basho_riak.list owner=root group=root mode=0644
#  when:
#    - not dist.stat.exists
#    - riak_install_package_cloud

#- name: Install Riak for Debian
#  package: "name={{ riak_package }} state=present update_cache=yes allow_unauthenticated=yes"
#  tags: Debian
#  when: "'deb' not in riak_package"

- name: "Copy deb file to server"
  become: true
  copy:
    src: "riak_2.2.3-1_amd64.deb"
    dest: "/tmp/riak_2.2.3-1_amd64.deb"
    owner: root
    group: root
    mode: 0500

- name: "Copy libssl deb file to server"
  become: true
  copy:
    src: "libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb"
    dest: "/tmp/libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb"
    owner: root
    group: root
    mode: 0500
  when: 'ansible_distribution_release != "xenial"'

- name: "Copy deb file to server"
  become: true
  copy:
    src: "libssl1.0-dev_1.0.2n-1ubuntu5.7_amd64.deb"
    dest: "/tmp/libssl1.0-dev_1.0.2n-1ubuntu5.7_amd64.deb"
    owner: root
    group: root
    mode: 0500
  when: 'ansible_distribution_release != "xenial"'

- name: Install old SSL for Focal 20.04
  apt:
    deb: "/tmp/libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb"
    allow_unauthenticated: yes
  tags: Debian
  when: 'ansible_distribution_release != "xenial"'

- name: Install old SSL dev for Focal 20.04
  apt:
    deb: "/tmp/libssl1.0-dev_1.0.2n-1ubuntu5.7_amd64.deb"
    allow_unauthenticated: yes
  tags: Debian
  when: 'ansible_distribution_release != "xenial"'

- name: Install Riak for Debian
  apt:
    deb: "/tmp/riak_2.2.3-1_amd64.deb"
    allow_unauthenticated: yes
  tags: Debian
  when:
    - not dist.stat.exists

- name: Set the riak ulimit for Debian
  copy: src=etc_security_limits.d_riak.conf dest=/etc/security/limits.d/riak.conf
  tags: Debian
  when: 'ansible_os_family == "Debian"'

- name: Set the riak ulimit for Ubuntu
  lineinfile: 'dest=/lib/systemd/system/riak.service line="LimitNOFILE=131072" insertafter="^RuntimeDirectory=riak"'
  tags: Debian
  when: 'ansible_distribution_release != "xenial" or ansible_distribution_release == "jessie"'
